redome:
  serviceRegistry:
    username: serviceregistry
    password: D4V5uzR4isTHS08WRKIInL1ZfP
  auth:
    jwtSecret: )J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%
    jwtExpirationMs: 14400000 

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${redome.serviceRegistry.username}:${redome.serviceRegistry.password}@localhost:8761/eureka"
  instance:
    hostname: localhost
