redome:
  serviceRegistry:
    username: serviceregistry
    password: "redome123sr"
  auth:
    jwtSecret: 3t6w9z$C&F)J@NcQfTjWnZr4u7x!A%D*G-KaPdSgUkXp2s5v8y/B?E(H+MbQeThW
    jwtExpirationMs: 14400000 

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${redome.serviceRegistry.username}:${redome.serviceRegistry.password}@localhost:8761/eureka"
  instance:
    hostname: localhost
