server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:oracle:thin:@10.46.9.63:1521/bdintra.inca.local
    username: modred_aplicacao
    password: euPwzh7F55
  jpa:
    driver: oracle.jdbc.driver.OracleDriver
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  # output:
  #   ansi:
  #     enabled: Always
  # rabbitmq:
  #   addresses: amqps://ihwpmkwj:43pU04U--tOS8gnKrH7Hj7KhV5Hjd167@beaver.rmq.cloudamqp.com/ihwpmkwj

logging:
  level:
    com.ead: INFO
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

# ead:
#   api:
#     url:
#       course: 'http://ead-course-service/ead-course'
#   broker:
#     exchange:
#       userEvent: ead.userevent
#       paymentEvent: ead.paymentevent
#     queue:
#      paymentEventQueue:
#         name: ead.paymentevent.ms.authuser

# authuser:
#   refreshscope:
#     name: Michelli Brito UPDATE!!!!!!!

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health


resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s