server:
  port: 8080

spring:
  application:
    name: redomenet-gateway-service
  cloud:
    gateway:
      routes:
        - id: service-authuserKKK
          uri: lb://REDOMENET-AUTHUSER-SERVICE
          predicates:
            - Path=/service-authuser/**
        - id: paciente-service
          uri: lb://REDOME-PACIENTE-SERVICE
          predicates:
            - Path=/redome-paciente/**
        - id: tarefa-service
          uri: lb://REDOME-TAREFA-SERVICE
          predicates:
            - Path=/redome-tarefa/**
