server:
  port: 8080

spring:
  application:
    name: redomenet-gateway-service
  cloud:
    gateway:
      routes:
        - id: redomenet-authuser
          uri: lb://REDOMENET-AUTHUSER-SERVICE
          predicates:
            - Path=/redomenet-authuser/**
        - id: redomenet-notificacao
          uri: lb://REDOMENET-NOTIFICACAO-SERVICE
          predicates:
            - Path=/redomenet-notificacao/**
        - id: redomenet-tarefa
          uri: lb://REDOMENET-TAREFA-SERVICE
          predicates:
            - Path=/redomenet-tarefa/**
