server:
  port: 8085
  servlet:
    context-path: "/redome-tarefa/"

spring:
  application:
    name: redome-tarefa-service
  datasource:
    url: jdbc:oracle:thin:@10.46.9.63:1521/bdintra.inca.local
    username: modred_aplicacao
    password: euPwzh7F55
  jpa:
    driver: oracle.jdbc.driver.OracleDriver
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
    properties:
      hibernate:
        show_sql: true

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
