server:
  port: 9082

spring:
  application:
    name: redomenet-gateway-service
  cloud:
    gateway:
      routes:
        - id: redomenet-authuser
          uri: lb://REDOMENET-AUTHUSER-SERVICE
          predicates:
            - Path=/redomenet-authuser/**
        - id: paciente-service
          uri: lb://REDOME-PACIENTE-SERVICE
          predicates:
            - Path=/redome-paciente/**
        - id: tarefa-service
          uri: lb://REDOME-TAREFA-SERVICE
          predicates:
            - Path=/redome-tarefa/**
